from pathlib import Path
from datetime import datetime

def write_docs(summaries: dict[str, str], output_path: Path):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Project Documentation\n",
        f"_Auto-generated by **ai-code-commenter** on {now}_\n",
        "\n---\n",
    ]

    for filename, summary in summaries.items():
        lines.append(f"## `{filename}`\n")
        lines.append(summary.strip() + "\n")
        lines.append("\n---\n")

    output_path.write_text("\n".join(lines), encoding="utf-8")